server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/studywithus
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 490665676025-6f9eoi9lgbl2m9bmpc5p41nhajoms2ns.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

          facebook:
            client-id: 978479829700927
            client-secret: d6ff48cb5ea64b3c2960b98cd4a6c124
            scope: public_profile,email

          naver:
            client-id: 9K5nZnVmg9ji6VKNhabp
            client-secret: dwOfGGNsB0
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace